name: Build and Publish to GHCR

on:
  push:
    branches: [ main ]  # Or your default branch

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read
  packages: write

jobs:
  build-and-push:
    outputs:
      imagename: ${{ steps.image_naming.outputs.imagename}}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: set vars
        id: image_naming
        run: |
          reponame=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')
          echo "imagename=ghcr.io/${reponame}/macrotracker-api:latest" >> $GITHUB_ENV
          echo "imagename=ghcr.io/${reponame}/macrotracker-api:latest" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          docker build -t ${imagename} .

      - name: Push Docker image to GHCR
        run: |
          docker push ${imagename}
  
  deploy:
    needs: build-and-push 
    uses: TConnellan/macro-tracker-backend/.github/workflows/deploy_image.yml@main
    with:
      environment: prod
      imagename: ${{ jobs.build-and-push.outputs.imagename }}
    secrets: inherit
